config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
   root 'pages#home'
   get 'about', to: 'pages#about'
  # get 'test', to: 'articles#test'
  # resources :articles , only: [ :index, :new, :create,:update,:edit,:test]# articles/1
  #  delete 'articles/:id' , to: 'articles#destroy'
  # delete 'articles/:id/delete' => 'articles#destroy', as: 'articles_delete'
  # get '/articles/:id/delete' => 'articles#destroy'
  resources :articles
=begin
  REST - Representational state transfer - mapping HTTP verbs (get, post, put/patch, delete)  
  to CRUD actions 
    resources porvides REST-ful routes to rails resources 
=end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true , length: {minimum: 6, maximum: 100}
    validates :description, presence: true , length: {minimum: 10, maximum: 300}
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
   
  def test
    end

    def show
    # byebug
    end
    def index
      @articles = Article.all
    end 
    
    def new
      @article =Article.new # initiat an @article instance variable for (@article.errors.any?) 
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        if @article.save
          flash[:notice] = "Article was created successfully."
          redirect_to @article
        else
          render 'new'
        end
    end

    def update
      if @article.update(article_params)
        flash[:notice] = "Article was updated successfully"
        redirect_to @article
      else
        render 'edit'
      end
    end

    def destroy
      @article.destroy
      flash[:succes] = "Article was  destroyed"
       redirect_to articles_path
    end

    private 
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end



  
=begin  
    # @article = Article.new(params.require(:article).permit(:title, :description))  
    # if  @article.save
    # flash[:notice] = "Article was created successfully. "
    # redirect_to article_path(@article) 
    # # redirect_to @article
    # else
    #  # byebug
    #   render 'new'
    #   #render_to_body 'new'
    end
=end


=begin
   => require the top level key off article and permit  title and description 
      #only the permitted attributes are passed into the model
      #What is params require in Rails?
      #In Rails, strong params provide an interface for protecting attributes from the end-user assignment.
      # We can specify required attributes and neglect unnecessary attributes to be used in the Active model mass assignment
      # (render plain: @article.inspect)
  
=end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about 
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @article, local: true)  do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/create.html.erb
<h1>create_page</h1>

app/views/articles/edit.html.erb
<h1>Create a new article</h1>

<%=render 'form'%> 
<%= link_to 'cancel and articles listing ', articles_path%>

app/views/articles/index.html.erb
<h1>article listing page</h1>
<table>
  <thead>
    <th>title</th>
    <th>description</th>
    <th colspan="3"> actions</th>
  </thead>
  <tbody>
    <% @articles.each do |article|%>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
     <td><%= link_to 'Show', article_path(article) %></td> 
     <td><%= link_to 'Edit', edit_article_path(article) %></td> 
      <td><%= link_to "Delete", article_path(article), data: {"turbo_method": :delete} %></td> 
    </tr>
    <% end %>
  </tbody>
</table>
<p>
<%= link_to 'Create new article', new_article_path%>
</p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>
<%=render 'form'%> 
<%= link_to 'articles listing ', articles_path%>

app/views/articles/show.html.erb
<h1>showing articles details</h1>

<!-- embedded ruby code if don't put = it evaluate that code 
                                     it doesn't say anything about displaying
                                    = this means evaluate and render to the screen -->
                                    
<p><%=@article.title%></p>         
<p><%=@article.description%></p>
<%= link_to 'Edit', edit_article_path(@article) , data: { confirm: "Are you sure?" }%> | 
<%= link_to 'Delelte' ,article_path(@article),data: {"turbo_method": :delete}%> | 
<%= link_to 'articles listing ', articles_path%>

app/views/articles/test.html.erb
<h1> test page</h1>

app/views/layouts/_messages.html.erb
    <% flash.each do |name , msg| %>
      <%= msg %>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">ALPHA BLOG</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>hello from about page </h1>

<%= link_to 'Article listing ', articles_path%>
<%= link_to 'Home page' , root_path %>

app/views/pages/home.html.erb
<h1> hello home page </h1>
<%= link_to 'Article listing ', articles_path%>
<%= link_to 'About page' , about_path %>